### ISSUE TITLE
Example page didn't work due to mixed content

### ISSUE THREAD

**Issue by BinotaLIU** [Mottie/javascript-number-formatter#13]
The example page didn't work on https connection dut to mixed content.
Need to use https to load resources:

![image](https://user-images.githubusercontent.com/3190556/39758861-afa06adc-5303-11e8-8fcb-f34b2f730be5.png)

**Comment by Mottie** [comment]
Hi @BinotaLIU!

Thanks for letting me know. It'll be fixed shortly.
