### ISSUE TITLE
Can you please publish the latest to npm?

### ISSUE THREAD

**Issue by jfstephe** [Mottie/javascript-number-formatter#16]
There's a confusing situation ATM where from npm you get 1.1.11 but the [jsfiddle](https://jsfiddle.net/Mottie/t2etyodx/) uses the github latest which says it's v 1.1.11 but I don't think it is as I think it's got the +/- sign change from about 6 months ago.

Can you publish the latest npm version please?

Thanks,
John

**Comment by Mottie** [comment]
Hi @jfstephe!

Yes, you're right! v1.1.12 is now available.

**Comment by jfstephe** [comment]
Thanks mate. That's awesome 😊

**Comment by Mottie** [comment]
Sorry, I'm gonna unpublish for now - see #17... I'll add an option to turn on & off the sign in mask behavior.
