### ISSUE TITLE
Should 1.1.12 have been a major version?

### ISSUE THREAD

**Issue by nathanpower** [Mottie/javascript-number-formatter#17]
The new handling of negative numbers seems like it should have been considered a breaking change.

**Comment by rankida** [comment]
Note the first example in the readme is now wrong.

```js
format( "#,##0.####", 1234567.890 );  // output: "1,234,567.89"
format( "$ #,###.00", -1234567.890 ); // output: "$ -1,234,567.89"
```

Please consider un-publishing and republishing as major

**Comment by Mottie** [comment]
Sorry! I totally forgot it was a breaking change.

I've unpublished for now. I'll add it back with a minor update and a new option to turn that behavior on & off.

**Comment by Veoth** [comment]
Hi, have you considered re-plublishing it ? 
I could use ts support !

Thanx

**Comment by josephpage** [comment]
@Mottie  Could you please publish the `2.0.0` release ? 🎉  
Negative and Positive Signs are a game-changing feature !

**Comment by Mottie** [comment]
Done... v2.0.0 has been released. I renamed the `ignoreSign` option to `enforceMaskSign` which is now `false` by default. Examples added to the [readme](https://github.com/Mottie/javascript-number-formatter#introduction).

**Comment by Mottie** [comment]
Hmm, wow... even though all the tests pass, the readme examples and behavior with the `enforceMaskSign` is not what I am expecting.

**Comment by Mottie** [comment]
Haha, nevermind... I forgot to update the readme examples.
