### ISSUE TITLE
Mask with # as decimal is not working as expected

### ISSUE THREAD

**Issue by Veoth** [Mottie/javascript-number-formatter#18]
Hi @Mottie ,
First thank you for the library which is really useful.

Among all the examples you supplied in the README, there is this one:

`format( "#,##0.####", 1234567.890 );  // output: "1,234,567.89"`

The actual output is "1,234,567.8900"

I believe this is a bug since the # should fill the decimal only if necessary.

**Comment by Mottie** [comment]
Hi @Veoth!

Thanks for reporting this problem! I'll get it fixed in the next release.
