### ISSUE TITLE
Remove trailing zeros for integer input OR improve documentation

### ISSUE THREAD

**Issue by mingos777** [Mottie/javascript-number-formatter#19]
In #18 trailing zeroes were supposedly fixed, however, I am unable to understand how to remove them completely when the input value is an integer. Here's my case:

```
expect(format("# ###,#", 19.9, {})).to.equal("19,9"); // pass
expect(format("# ###,#", 20, {})).to.equal("20"); // fail; actual output: "20,0"
```

I assume I'm not asking for something that your tool cannot do, but the documentation fails to explain the formatting strings. I do not understand what the various symbols (`#` vs `0`) mean and how to use them to achieve what I need.

**Comment by Mottie** [comment]
Hi @mingos777!

Thanks for reporting this problem. It was not behaving as expected. Version 2.0.7 was just released and will now behave as expected.

**Comment by Mottie** [comment]
Also, let me know if the new ["format symbols"](https://github.com/Mottie/javascript-number-formatter#format-symbols) section in the readme is sufficient.

**Comment by mingos777** [comment]
I have confirmed that version 2.0.7 behaves as expected.
The new doc section makes formatting options clear, thank you very much!
