### ISSUE TITLE
Improve TypeScript bindings

### ISSUE THREAD

**Issue by mingos777** [Mottie/javascript-number-formatter#20]
Current TypeScript typings mark the third parametre to the `format` function as required. However, as shown in the doc, it is clearly optional. It should be marked as optional in the TS typings as well.

In TS, in stead of writing:

```
format("# ###,#", 19.9, {});
```

I would like to be able to write:

```
format("# ###,#", 19.9);
```

**Comment by Mottie** [comment]
Hi @mingos777!

Thanks for reporting this problem! I haven't used typescript, so I'd appreciate it if you would verify everything is working as expected now - https://github.com/Mottie/javascript-number-formatter/blob/master/index.d.ts

Thanks!

**Comment by mingos777** [comment]
The TS typings are correct as of version 2.0.7 and I can omit the last argument without raising a compilation error.
Thank you for the quick reaction.
