### ISSUE TITLE
ES6 grammar exists in lib/format.min.js (=>)

### ISSUE THREAD

**Issue by raisezhang** [Mottie/javascript-number-formatter#24]
This should not include ES6 grammar?    such as arrow functions (=>) ,  Thanks     

```
https://github.com/Mottie/javascript-number-formatter/blob/master/lib/format.min.js
````

**Comment by Mottie** [comment]
Hi @raisezhang!

Yes, most browsers support it. If you need es5 support, use [format.es5.js](https://github.com/Mottie/javascript-number-formatter/blob/master/lib/format.es5.js). Also see #21.

**Comment by raisezhang** [comment]
How to configure ```webpack``` reference ``` format.es5.js``` file?

**Comment by Mottie** [comment]
This repo uses [rollup](https://github.com/Mottie/javascript-number-formatter/blob/master/rollup.config.js).
