### ISSUE TITLE
Npm version not working

### ISSUE THREAD

**Issue by doArcanjo** [Mottie/javascript-number-formatter#3]
Check Npm package!

**Comment by Mottie** [comment]
Hi @doArcanjo!

Thanks! I'll get this fixed ASAP!

**Comment by Mottie** [comment]
Ok, I've verified that it's working now...

quick online test here: https://tonicdev.com/npm/number-format.js

```js
require("number-format.js")( "#,##0.####", 1234567.890 );
// result: "1,234,567.89"
```

**Comment by doArcanjo** [comment]
No problem, keep up the good work!
